name = "cloudflare-blog"
compatibility_date = "2025-08-26"
main = "index.js"

[assets]
  directory = "."
  include = ["**/*"]
  exclude = ["node_modules/**", ".git/**"]

[build]
  command = "npm run build"
  cwd = ""
  upload = {\ format = "service-worker", main = "index.js" }